-- +goose Up
ALTER TABLE colors
    ADD COLUMN IF NOT EXISTS hex TEXT NOT NULL DEFAULT '#000000';

ALTER TABLE patterns
    ADD COLUMN IF NOT EXISTS icon_key TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE patterns
    DROP COLUMN IF EXISTS icon_key;

ALTER TABLE colors
    DROP COLUMN IF EXISTS hex;
