// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: acl.proto

package aclpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MembershipStatus int32

const (
	MembershipStatus_MEMBERSHIP_STATUS_UNSPECIFIED MembershipStatus = 0
	MembershipStatus_MEMBERSHIP_STATUS_ACTIVE      MembershipStatus = 1
	MembershipStatus_MEMBERSHIP_STATUS_REMOVED     MembershipStatus = 2
)

// Enum value maps for MembershipStatus.
var (
	MembershipStatus_name = map[int32]string{
		0: "MEMBERSHIP_STATUS_UNSPECIFIED",
		1: "MEMBERSHIP_STATUS_ACTIVE",
		2: "MEMBERSHIP_STATUS_REMOVED",
	}
	MembershipStatus_value = map[string]int32{
		"MEMBERSHIP_STATUS_UNSPECIFIED": 0,
		"MEMBERSHIP_STATUS_ACTIVE":      1,
		"MEMBERSHIP_STATUS_REMOVED":     2,
	}
)

func (x MembershipStatus) Enum() *MembershipStatus {
	p := new(MembershipStatus)
	*p = x
	return p
}

func (x MembershipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MembershipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[0].Descriptor()
}

func (MembershipStatus) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[0]
}

func (x MembershipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MembershipStatus.Descriptor instead.
func (MembershipStatus) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

type RoleKind int32

const (
	RoleKind_ROLE_KIND_UNSPECIFIED RoleKind = 0
	RoleKind_ROLE_KIND_SYSTEM      RoleKind = 1
	RoleKind_ROLE_KIND_CUSTOM      RoleKind = 2
)

// Enum value maps for RoleKind.
var (
	RoleKind_name = map[int32]string{
		0: "ROLE_KIND_UNSPECIFIED",
		1: "ROLE_KIND_SYSTEM",
		2: "ROLE_KIND_CUSTOM",
	}
	RoleKind_value = map[string]int32{
		"ROLE_KIND_UNSPECIFIED": 0,
		"ROLE_KIND_SYSTEM":      1,
		"ROLE_KIND_CUSTOM":      2,
	}
)

func (x RoleKind) Enum() *RoleKind {
	p := new(RoleKind)
	*p = x
	return p
}

func (x RoleKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[1].Descriptor()
}

func (RoleKind) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[1]
}

func (x RoleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleKind.Descriptor instead.
func (RoleKind) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED              Action = 0
	Action_ACTION_PET_READ                 Action = 1
	Action_ACTION_PET_EDIT                 Action = 2
	Action_ACTION_PET_STATUS_CHANGE        Action = 3
	Action_ACTION_PET_DELETE               Action = 4
	Action_ACTION_LOG_READ                 Action = 5
	Action_ACTION_LOG_CREATE               Action = 6
	Action_ACTION_LOG_EDIT                 Action = 7
	Action_ACTION_LOG_DELETE               Action = 8
	Action_ACTION_LOG_ATTACHMENTS_READ     Action = 9
	Action_ACTION_HEALTH_READ              Action = 10
	Action_ACTION_HEALTH_WRITE             Action = 11
	Action_ACTION_TASK_READ                Action = 12
	Action_ACTION_TASK_WRITE               Action = 13
	Action_ACTION_MEMBERS_VIEW             Action = 14
	Action_ACTION_MEMBERS_INVITE           Action = 15
	Action_ACTION_MEMBERS_REMOVE           Action = 16
	Action_ACTION_MEMBERS_EDIT_PERMISSIONS Action = 17
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		1:  "ACTION_PET_READ",
		2:  "ACTION_PET_EDIT",
		3:  "ACTION_PET_STATUS_CHANGE",
		4:  "ACTION_PET_DELETE",
		5:  "ACTION_LOG_READ",
		6:  "ACTION_LOG_CREATE",
		7:  "ACTION_LOG_EDIT",
		8:  "ACTION_LOG_DELETE",
		9:  "ACTION_LOG_ATTACHMENTS_READ",
		10: "ACTION_HEALTH_READ",
		11: "ACTION_HEALTH_WRITE",
		12: "ACTION_TASK_READ",
		13: "ACTION_TASK_WRITE",
		14: "ACTION_MEMBERS_VIEW",
		15: "ACTION_MEMBERS_INVITE",
		16: "ACTION_MEMBERS_REMOVE",
		17: "ACTION_MEMBERS_EDIT_PERMISSIONS",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":              0,
		"ACTION_PET_READ":                 1,
		"ACTION_PET_EDIT":                 2,
		"ACTION_PET_STATUS_CHANGE":        3,
		"ACTION_PET_DELETE":               4,
		"ACTION_LOG_READ":                 5,
		"ACTION_LOG_CREATE":               6,
		"ACTION_LOG_EDIT":                 7,
		"ACTION_LOG_DELETE":               8,
		"ACTION_LOG_ATTACHMENTS_READ":     9,
		"ACTION_HEALTH_READ":              10,
		"ACTION_HEALTH_WRITE":             11,
		"ACTION_TASK_READ":                12,
		"ACTION_TASK_WRITE":               13,
		"ACTION_MEMBERS_VIEW":             14,
		"ACTION_MEMBERS_INVITE":           15,
		"ACTION_MEMBERS_REMOVE":           16,
		"ACTION_MEMBERS_EDIT_PERMISSIONS": 17,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[2].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[2]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{2}
}

type Policy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PetRead                bool                   `protobuf:"varint,1,opt,name=pet_read,json=petRead,proto3" json:"pet_read,omitempty"`
	PetEdit                bool                   `protobuf:"varint,2,opt,name=pet_edit,json=petEdit,proto3" json:"pet_edit,omitempty"`
	PetStatusChange        bool                   `protobuf:"varint,3,opt,name=pet_status_change,json=petStatusChange,proto3" json:"pet_status_change,omitempty"`
	PetDelete              bool                   `protobuf:"varint,4,opt,name=pet_delete,json=petDelete,proto3" json:"pet_delete,omitempty"`
	LogRead                bool                   `protobuf:"varint,5,opt,name=log_read,json=logRead,proto3" json:"log_read,omitempty"`
	LogCreate              bool                   `protobuf:"varint,6,opt,name=log_create,json=logCreate,proto3" json:"log_create,omitempty"`
	LogEdit                bool                   `protobuf:"varint,7,opt,name=log_edit,json=logEdit,proto3" json:"log_edit,omitempty"`
	LogDelete              bool                   `protobuf:"varint,8,opt,name=log_delete,json=logDelete,proto3" json:"log_delete,omitempty"`
	LogAttachmentsRead     bool                   `protobuf:"varint,9,opt,name=log_attachments_read,json=logAttachmentsRead,proto3" json:"log_attachments_read,omitempty"`
	HealthRead             bool                   `protobuf:"varint,10,opt,name=health_read,json=healthRead,proto3" json:"health_read,omitempty"`
	HealthWrite            bool                   `protobuf:"varint,11,opt,name=health_write,json=healthWrite,proto3" json:"health_write,omitempty"`
	TaskRead               bool                   `protobuf:"varint,12,opt,name=task_read,json=taskRead,proto3" json:"task_read,omitempty"`
	TaskWrite              bool                   `protobuf:"varint,13,opt,name=task_write,json=taskWrite,proto3" json:"task_write,omitempty"`
	MembersView            bool                   `protobuf:"varint,14,opt,name=members_view,json=membersView,proto3" json:"members_view,omitempty"`
	MembersInvite          bool                   `protobuf:"varint,15,opt,name=members_invite,json=membersInvite,proto3" json:"members_invite,omitempty"`
	MembersRemove          bool                   `protobuf:"varint,16,opt,name=members_remove,json=membersRemove,proto3" json:"members_remove,omitempty"`
	MembersEditPermissions bool                   `protobuf:"varint,17,opt,name=members_edit_permissions,json=membersEditPermissions,proto3" json:"members_edit_permissions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetPetRead() bool {
	if x != nil {
		return x.PetRead
	}
	return false
}

func (x *Policy) GetPetEdit() bool {
	if x != nil {
		return x.PetEdit
	}
	return false
}

func (x *Policy) GetPetStatusChange() bool {
	if x != nil {
		return x.PetStatusChange
	}
	return false
}

func (x *Policy) GetPetDelete() bool {
	if x != nil {
		return x.PetDelete
	}
	return false
}

func (x *Policy) GetLogRead() bool {
	if x != nil {
		return x.LogRead
	}
	return false
}

func (x *Policy) GetLogCreate() bool {
	if x != nil {
		return x.LogCreate
	}
	return false
}

func (x *Policy) GetLogEdit() bool {
	if x != nil {
		return x.LogEdit
	}
	return false
}

func (x *Policy) GetLogDelete() bool {
	if x != nil {
		return x.LogDelete
	}
	return false
}

func (x *Policy) GetLogAttachmentsRead() bool {
	if x != nil {
		return x.LogAttachmentsRead
	}
	return false
}

func (x *Policy) GetHealthRead() bool {
	if x != nil {
		return x.HealthRead
	}
	return false
}

func (x *Policy) GetHealthWrite() bool {
	if x != nil {
		return x.HealthWrite
	}
	return false
}

func (x *Policy) GetTaskRead() bool {
	if x != nil {
		return x.TaskRead
	}
	return false
}

func (x *Policy) GetTaskWrite() bool {
	if x != nil {
		return x.TaskWrite
	}
	return false
}

func (x *Policy) GetMembersView() bool {
	if x != nil {
		return x.MembersView
	}
	return false
}

func (x *Policy) GetMembersInvite() bool {
	if x != nil {
		return x.MembersInvite
	}
	return false
}

func (x *Policy) GetMembersRemove() bool {
	if x != nil {
		return x.MembersRemove
	}
	return false
}

func (x *Policy) GetMembersEditPermissions() bool {
	if x != nil {
		return x.MembersEditPermissions
	}
	return false
}

type Role struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            RoleKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=acl.RoleKind" json:"kind,omitempty"`
	PetId           string                 `protobuf:"bytes,3,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Code            string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,6,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetKind() RoleKind {
	if x != nil {
		return x.Kind
	}
	return RoleKind_ROLE_KIND_UNSPECIFIED
}

func (x *Role) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Role) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

type PetMembership struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PetId          string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Status         MembershipStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=acl.MembershipStatus" json:"status,omitempty"`
	IsPrimaryOwner bool                   `protobuf:"varint,4,opt,name=is_primary_owner,json=isPrimaryOwner,proto3" json:"is_primary_owner,omitempty"`
	Role           *Role                  `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Policy         *Policy                `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PetMembership) Reset() {
	*x = PetMembership{}
	mi := &file_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetMembership) ProtoMessage() {}

func (x *PetMembership) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetMembership.ProtoReflect.Descriptor instead.
func (*PetMembership) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{2}
}

func (x *PetMembership) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *PetMembership) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PetMembership) GetStatus() MembershipStatus {
	if x != nil {
		return x.Status
	}
	return MembershipStatus_MEMBERSHIP_STATUS_UNSPECIFIED
}

func (x *PetMembership) GetIsPrimaryOwner() bool {
	if x != nil {
		return x.IsPrimaryOwner
	}
	return false
}

func (x *PetMembership) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *PetMembership) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_acl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{3}
}

func (x *IsMemberRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_acl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{4}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_acl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{5}
}

func (x *GetPolicyRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *GetPolicyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPolicyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberId       string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Status         MembershipStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=acl.MembershipStatus" json:"status,omitempty"`
	IsPrimaryOwner bool                   `protobuf:"varint,3,opt,name=is_primary_owner,json=isPrimaryOwner,proto3" json:"is_primary_owner,omitempty"`
	Policy         *Policy                `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_acl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{6}
}

func (x *GetPolicyResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetPolicyResponse) GetStatus() MembershipStatus {
	if x != nil {
		return x.Status
	}
	return MembershipStatus_MEMBERSHIP_STATUS_UNSPECIFIED
}

func (x *GetPolicyResponse) GetIsPrimaryOwner() bool {
	if x != nil {
		return x.IsPrimaryOwner
	}
	return false
}

func (x *GetPolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=acl.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_acl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{7}
}

func (x *CheckRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *CheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_acl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{8}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type ListPetsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsForUserRequest) Reset() {
	*x = ListPetsForUserRequest{}
	mi := &file_acl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsForUserRequest) ProtoMessage() {}

func (x *ListPetsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsForUserRequest.ProtoReflect.Descriptor instead.
func (*ListPetsForUserRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{9}
}

func (x *ListPetsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPetsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetIds        []string               `protobuf:"bytes,1,rep,name=pet_ids,json=petIds,proto3" json:"pet_ids,omitempty"`
	Memberships   []*PetMembership       `protobuf:"bytes,2,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsForUserResponse) Reset() {
	*x = ListPetsForUserResponse{}
	mi := &file_acl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsForUserResponse) ProtoMessage() {}

func (x *ListPetsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsForUserResponse.ProtoReflect.Descriptor instead.
func (*ListPetsForUserResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{10}
}

func (x *ListPetsForUserResponse) GetPetIds() []string {
	if x != nil {
		return x.PetIds
	}
	return nil
}

func (x *ListPetsForUserResponse) GetMemberships() []*PetMembership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

type CreateOwnerMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerMembershipRequest) Reset() {
	*x = CreateOwnerMembershipRequest{}
	mi := &file_acl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerMembershipRequest) ProtoMessage() {}

func (x *CreateOwnerMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateOwnerMembershipRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{11}
}

func (x *CreateOwnerMembershipRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *CreateOwnerMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateOwnerMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerMembershipResponse) Reset() {
	*x = CreateOwnerMembershipResponse{}
	mi := &file_acl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerMembershipResponse) ProtoMessage() {}

func (x *CreateOwnerMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerMembershipResponse.ProtoReflect.Descriptor instead.
func (*CreateOwnerMembershipResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOwnerMembershipResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_acl_proto protoreflect.FileDescriptor

const file_acl_proto_rawDesc = "" +
	"\n" +
	"\tacl.proto\x12\x03acl\"\xda\x04\n" +
	"\x06Policy\x12\x19\n" +
	"\bpet_read\x18\x01 \x01(\bR\apetRead\x12\x19\n" +
	"\bpet_edit\x18\x02 \x01(\bR\apetEdit\x12*\n" +
	"\x11pet_status_change\x18\x03 \x01(\bR\x0fpetStatusChange\x12\x1d\n" +
	"\n" +
	"pet_delete\x18\x04 \x01(\bR\tpetDelete\x12\x19\n" +
	"\blog_read\x18\x05 \x01(\bR\alogRead\x12\x1d\n" +
	"\n" +
	"log_create\x18\x06 \x01(\bR\tlogCreate\x12\x19\n" +
	"\blog_edit\x18\a \x01(\bR\alogEdit\x12\x1d\n" +
	"\n" +
	"log_delete\x18\b \x01(\bR\tlogDelete\x120\n" +
	"\x14log_attachments_read\x18\t \x01(\bR\x12logAttachmentsRead\x12\x1f\n" +
	"\vhealth_read\x18\n" +
	" \x01(\bR\n" +
	"healthRead\x12!\n" +
	"\fhealth_write\x18\v \x01(\bR\vhealthWrite\x12\x1b\n" +
	"\ttask_read\x18\f \x01(\bR\btaskRead\x12\x1d\n" +
	"\n" +
	"task_write\x18\r \x01(\bR\ttaskWrite\x12!\n" +
	"\fmembers_view\x18\x0e \x01(\bR\vmembersView\x12%\n" +
	"\x0emembers_invite\x18\x0f \x01(\bR\rmembersInvite\x12%\n" +
	"\x0emembers_remove\x18\x10 \x01(\bR\rmembersRemove\x128\n" +
	"\x18members_edit_permissions\x18\x11 \x01(\bR\x16membersEditPermissions\"\xa7\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04kind\x18\x02 \x01(\x0e2\r.acl.RoleKindR\x04kind\x12\x15\n" +
	"\x06pet_id\x18\x03 \x01(\tR\x05petId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12+\n" +
	"\x12created_by_user_id\x18\x06 \x01(\tR\x0fcreatedByUserId\"\xe0\x01\n" +
	"\rPetMembership\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.acl.MembershipStatusR\x06status\x12(\n" +
	"\x10is_primary_owner\x18\x04 \x01(\bR\x0eisPrimaryOwner\x12\x1d\n" +
	"\x04role\x18\x05 \x01(\v2\t.acl.RoleR\x04role\x12#\n" +
	"\x06policy\x18\x06 \x01(\v2\v.acl.PolicyR\x06policy\"A\n" +
	"\x0fIsMemberRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"B\n" +
	"\x10GetPolicyRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xae\x01\n" +
	"\x11GetPolicyResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.acl.MembershipStatusR\x06status\x12(\n" +
	"\x10is_primary_owner\x18\x03 \x01(\bR\x0eisPrimaryOwner\x12#\n" +
	"\x06policy\x18\x04 \x01(\v2\v.acl.PolicyR\x06policy\"c\n" +
	"\fCheckRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\x06action\x18\x03 \x01(\x0e2\v.acl.ActionR\x06action\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"1\n" +
	"\x16ListPetsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"h\n" +
	"\x17ListPetsForUserResponse\x12\x17\n" +
	"\apet_ids\x18\x01 \x03(\tR\x06petIds\x124\n" +
	"\vmemberships\x18\x02 \x03(\v2\x12.acl.PetMembershipR\vmemberships\"N\n" +
	"\x1cCreateOwnerMembershipRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"<\n" +
	"\x1dCreateOwnerMembershipResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId*r\n" +
	"\x10MembershipStatus\x12!\n" +
	"\x1dMEMBERSHIP_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MEMBERSHIP_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19MEMBERSHIP_STATUS_REMOVED\x10\x02*Q\n" +
	"\bRoleKind\x12\x19\n" +
	"\x15ROLE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROLE_KIND_SYSTEM\x10\x01\x12\x14\n" +
	"\x10ROLE_KIND_CUSTOM\x10\x02*\xca\x03\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_PET_READ\x10\x01\x12\x13\n" +
	"\x0fACTION_PET_EDIT\x10\x02\x12\x1c\n" +
	"\x18ACTION_PET_STATUS_CHANGE\x10\x03\x12\x15\n" +
	"\x11ACTION_PET_DELETE\x10\x04\x12\x13\n" +
	"\x0fACTION_LOG_READ\x10\x05\x12\x15\n" +
	"\x11ACTION_LOG_CREATE\x10\x06\x12\x13\n" +
	"\x0fACTION_LOG_EDIT\x10\a\x12\x15\n" +
	"\x11ACTION_LOG_DELETE\x10\b\x12\x1f\n" +
	"\x1bACTION_LOG_ATTACHMENTS_READ\x10\t\x12\x16\n" +
	"\x12ACTION_HEALTH_READ\x10\n" +
	"\x12\x17\n" +
	"\x13ACTION_HEALTH_WRITE\x10\v\x12\x14\n" +
	"\x10ACTION_TASK_READ\x10\f\x12\x15\n" +
	"\x11ACTION_TASK_WRITE\x10\r\x12\x17\n" +
	"\x13ACTION_MEMBERS_VIEW\x10\x0e\x12\x19\n" +
	"\x15ACTION_MEMBERS_INVITE\x10\x0f\x12\x19\n" +
	"\x15ACTION_MEMBERS_REMOVE\x10\x10\x12#\n" +
	"\x1fACTION_MEMBERS_EDIT_PERMISSIONS\x10\x112\xdf\x02\n" +
	"\n" +
	"ACLService\x127\n" +
	"\bIsMember\x12\x14.acl.IsMemberRequest\x1a\x15.acl.IsMemberResponse\x12:\n" +
	"\tGetPolicy\x12\x15.acl.GetPolicyRequest\x1a\x16.acl.GetPolicyResponse\x12.\n" +
	"\x05Check\x12\x11.acl.CheckRequest\x1a\x12.acl.CheckResponse\x12L\n" +
	"\x0fListPetsForUser\x12\x1b.acl.ListPetsForUserRequest\x1a\x1c.acl.ListPetsForUserResponse\x12^\n" +
	"\x15CreateOwnerMembership\x12!.acl.CreateOwnerMembershipRequest\x1a\".acl.CreateOwnerMembershipResponseB\x11Z\x0facl/proto;aclpbb\x06proto3"

var (
	file_acl_proto_rawDescOnce sync.Once
	file_acl_proto_rawDescData []byte
)

func file_acl_proto_rawDescGZIP() []byte {
	file_acl_proto_rawDescOnce.Do(func() {
		file_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)))
	})
	return file_acl_proto_rawDescData
}

var file_acl_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_acl_proto_goTypes = []any{
	(MembershipStatus)(0),                 // 0: acl.MembershipStatus
	(RoleKind)(0),                         // 1: acl.RoleKind
	(Action)(0),                           // 2: acl.Action
	(*Policy)(nil),                        // 3: acl.Policy
	(*Role)(nil),                          // 4: acl.Role
	(*PetMembership)(nil),                 // 5: acl.PetMembership
	(*IsMemberRequest)(nil),               // 6: acl.IsMemberRequest
	(*IsMemberResponse)(nil),              // 7: acl.IsMemberResponse
	(*GetPolicyRequest)(nil),              // 8: acl.GetPolicyRequest
	(*GetPolicyResponse)(nil),             // 9: acl.GetPolicyResponse
	(*CheckRequest)(nil),                  // 10: acl.CheckRequest
	(*CheckResponse)(nil),                 // 11: acl.CheckResponse
	(*ListPetsForUserRequest)(nil),        // 12: acl.ListPetsForUserRequest
	(*ListPetsForUserResponse)(nil),       // 13: acl.ListPetsForUserResponse
	(*CreateOwnerMembershipRequest)(nil),  // 14: acl.CreateOwnerMembershipRequest
	(*CreateOwnerMembershipResponse)(nil), // 15: acl.CreateOwnerMembershipResponse
}
var file_acl_proto_depIdxs = []int32{
	1,  // 0: acl.Role.kind:type_name -> acl.RoleKind
	0,  // 1: acl.PetMembership.status:type_name -> acl.MembershipStatus
	4,  // 2: acl.PetMembership.role:type_name -> acl.Role
	3,  // 3: acl.PetMembership.policy:type_name -> acl.Policy
	0,  // 4: acl.GetPolicyResponse.status:type_name -> acl.MembershipStatus
	3,  // 5: acl.GetPolicyResponse.policy:type_name -> acl.Policy
	2,  // 6: acl.CheckRequest.action:type_name -> acl.Action
	5,  // 7: acl.ListPetsForUserResponse.memberships:type_name -> acl.PetMembership
	6,  // 8: acl.ACLService.IsMember:input_type -> acl.IsMemberRequest
	8,  // 9: acl.ACLService.GetPolicy:input_type -> acl.GetPolicyRequest
	10, // 10: acl.ACLService.Check:input_type -> acl.CheckRequest
	12, // 11: acl.ACLService.ListPetsForUser:input_type -> acl.ListPetsForUserRequest
	14, // 12: acl.ACLService.CreateOwnerMembership:input_type -> acl.CreateOwnerMembershipRequest
	7,  // 13: acl.ACLService.IsMember:output_type -> acl.IsMemberResponse
	9,  // 14: acl.ACLService.GetPolicy:output_type -> acl.GetPolicyResponse
	11, // 15: acl.ACLService.Check:output_type -> acl.CheckResponse
	13, // 16: acl.ACLService.ListPetsForUser:output_type -> acl.ListPetsForUserResponse
	15, // 17: acl.ACLService.CreateOwnerMembership:output_type -> acl.CreateOwnerMembershipResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_acl_proto_init() }
func file_acl_proto_init() {
	if File_acl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acl_proto_goTypes,
		DependencyIndexes: file_acl_proto_depIdxs,
		EnumInfos:         file_acl_proto_enumTypes,
		MessageInfos:      file_acl_proto_msgTypes,
	}.Build()
	File_acl_proto = out.File
	file_acl_proto_goTypes = nil
	file_acl_proto_depIdxs = nil
}
