// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: petpb/pet.proto

package petpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchGetBriefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetIds        []string               `protobuf:"bytes,1,rep,name=pet_ids,json=petIds,proto3" json:"pet_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetBriefRequest) Reset() {
	*x = BatchGetBriefRequest{}
	mi := &file_petpb_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBriefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBriefRequest) ProtoMessage() {}

func (x *BatchGetBriefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_petpb_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBriefRequest.ProtoReflect.Descriptor instead.
func (*BatchGetBriefRequest) Descriptor() ([]byte, []int) {
	return file_petpb_pet_proto_rawDescGZIP(), []int{0}
}

func (x *BatchGetBriefRequest) GetPetIds() []string {
	if x != nil {
		return x.PetIds
	}
	return nil
}

type PetBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetBrief) Reset() {
	*x = PetBrief{}
	mi := &file_petpb_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetBrief) ProtoMessage() {}

func (x *PetBrief) ProtoReflect() protoreflect.Message {
	mi := &file_petpb_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetBrief.ProtoReflect.Descriptor instead.
func (*PetBrief) Descriptor() ([]byte, []int) {
	return file_petpb_pet_proto_rawDescGZIP(), []int{1}
}

func (x *PetBrief) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *PetBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetBrief) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type BatchGetBriefResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*PetBrief            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NotFoundPetIds []string               `protobuf:"bytes,2,rep,name=not_found_pet_ids,json=notFoundPetIds,proto3" json:"not_found_pet_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchGetBriefResponse) Reset() {
	*x = BatchGetBriefResponse{}
	mi := &file_petpb_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetBriefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetBriefResponse) ProtoMessage() {}

func (x *BatchGetBriefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_petpb_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetBriefResponse.ProtoReflect.Descriptor instead.
func (*BatchGetBriefResponse) Descriptor() ([]byte, []int) {
	return file_petpb_pet_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetBriefResponse) GetItems() []*PetBrief {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchGetBriefResponse) GetNotFoundPetIds() []string {
	if x != nil {
		return x.NotFoundPetIds
	}
	return nil
}

var File_petpb_pet_proto protoreflect.FileDescriptor

const file_petpb_pet_proto_rawDesc = "" +
	"\n" +
	"\x0fpetpb/pet.proto\x12\x03pet\"/\n" +
	"\x14BatchGetBriefRequest\x12\x17\n" +
	"\apet_ids\x18\x01 \x03(\tR\x06petIds\"T\n" +
	"\bPetBrief\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"g\n" +
	"\x15BatchGetBriefResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.pet.PetBriefR\x05items\x12)\n" +
	"\x11not_found_pet_ids\x18\x02 \x03(\tR\x0enotFoundPetIds2T\n" +
	"\n" +
	"PetService\x12F\n" +
	"\rBatchGetBrief\x12\x19.pet.BatchGetBriefRequest\x1a\x1a.pet.BatchGetBriefResponseB\x17Z\x15pawly/pkg/petpb;petpbb\x06proto3"

var (
	file_petpb_pet_proto_rawDescOnce sync.Once
	file_petpb_pet_proto_rawDescData []byte
)

func file_petpb_pet_proto_rawDescGZIP() []byte {
	file_petpb_pet_proto_rawDescOnce.Do(func() {
		file_petpb_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_petpb_pet_proto_rawDesc), len(file_petpb_pet_proto_rawDesc)))
	})
	return file_petpb_pet_proto_rawDescData
}

var file_petpb_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_petpb_pet_proto_goTypes = []any{
	(*BatchGetBriefRequest)(nil),  // 0: pet.BatchGetBriefRequest
	(*PetBrief)(nil),              // 1: pet.PetBrief
	(*BatchGetBriefResponse)(nil), // 2: pet.BatchGetBriefResponse
}
var file_petpb_pet_proto_depIdxs = []int32{
	1, // 0: pet.BatchGetBriefResponse.items:type_name -> pet.PetBrief
	0, // 1: pet.PetService.BatchGetBrief:input_type -> pet.BatchGetBriefRequest
	2, // 2: pet.PetService.BatchGetBrief:output_type -> pet.BatchGetBriefResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_petpb_pet_proto_init() }
func file_petpb_pet_proto_init() {
	if File_petpb_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_petpb_pet_proto_rawDesc), len(file_petpb_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_petpb_pet_proto_goTypes,
		DependencyIndexes: file_petpb_pet_proto_depIdxs,
		MessageInfos:      file_petpb_pet_proto_msgTypes,
	}.Build()
	File_petpb_pet_proto = out.File
	file_petpb_pet_proto_goTypes = nil
	file_petpb_pet_proto_depIdxs = nil
}
