// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: file.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_UPLOADING   FileStatus = 1
	FileStatus_FILE_STATUS_READY       FileStatus = 2
	FileStatus_FILE_STATUS_FAILED      FileStatus = 3
	FileStatus_FILE_STATUS_DELETED     FileStatus = 4
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_UPLOADING",
		2: "FILE_STATUS_READY",
		3: "FILE_STATUS_FAILED",
		4: "FILE_STATUS_DELETED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_UPLOADING":   1,
		"FILE_STATUS_READY":       2,
		"FILE_STATUS_FAILED":      3,
		"FILE_STATUS_DELETED":     4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[0].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[0]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

type OwnerService int32

const (
	OwnerService_OWNER_SERVICE_UNSPECIFIED OwnerService = 0
	OwnerService_OWNER_SERVICE_PROFILE     OwnerService = 1
	OwnerService_OWNER_SERVICE_PET         OwnerService = 2
	OwnerService_OWNER_SERVICE_GUIDE       OwnerService = 3
	OwnerService_OWNER_SERVICE_LOG         OwnerService = 4
	OwnerService_OWNER_SERVICE_HEALTH      OwnerService = 5
	OwnerService_OWNER_SERVICE_CHAT        OwnerService = 6
	OwnerService_OWNER_SERVICE_CATALOG     OwnerService = 7
)

// Enum value maps for OwnerService.
var (
	OwnerService_name = map[int32]string{
		0: "OWNER_SERVICE_UNSPECIFIED",
		1: "OWNER_SERVICE_PROFILE",
		2: "OWNER_SERVICE_PET",
		3: "OWNER_SERVICE_GUIDE",
		4: "OWNER_SERVICE_LOG",
		5: "OWNER_SERVICE_HEALTH",
		6: "OWNER_SERVICE_CHAT",
		7: "OWNER_SERVICE_CATALOG",
	}
	OwnerService_value = map[string]int32{
		"OWNER_SERVICE_UNSPECIFIED": 0,
		"OWNER_SERVICE_PROFILE":     1,
		"OWNER_SERVICE_PET":         2,
		"OWNER_SERVICE_GUIDE":       3,
		"OWNER_SERVICE_LOG":         4,
		"OWNER_SERVICE_HEALTH":      5,
		"OWNER_SERVICE_CHAT":        6,
		"OWNER_SERVICE_CATALOG":     7,
	}
)

func (x OwnerService) Enum() *OwnerService {
	p := new(OwnerService)
	*p = x
	return p
}

func (x OwnerService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OwnerService) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[1].Descriptor()
}

func (OwnerService) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[1]
}

func (x OwnerService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OwnerService.Descriptor instead.
func (OwnerService) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

type FileObject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          FileStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=file.FileStatus" json:"status,omitempty"`
	MimeType        string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes       int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Bucket          string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey       string                 `protobuf:"bytes,6,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,7,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UploadExpiresAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=upload_expires_at,json=uploadExpiresAt,proto3" json:"upload_expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileObject) Reset() {
	*x = FileObject{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileObject) ProtoMessage() {}

func (x *FileObject) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileObject.ProtoReflect.Descriptor instead.
func (*FileObject) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileObject) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileObject) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileObject) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileObject) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileObject) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *FileObject) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *FileObject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileObject) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FileObject) GetUploadExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadExpiresAt
	}
	return nil
}

type FileLink struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerService    OwnerService           `protobuf:"varint,3,opt,name=owner_service,json=ownerService,proto3,enum=file.OwnerService" json:"owner_service,omitempty"`
	OwnerType       string                 `protobuf:"bytes,4,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId         string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PetId           string                 `protobuf:"bytes,6,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,7,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileLink) Reset() {
	*x = FileLink{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLink) ProtoMessage() {}

func (x *FileLink) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLink.ProtoReflect.Descriptor instead.
func (*FileLink) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileLink) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileLink) GetOwnerService() OwnerService {
	if x != nil {
		return x.OwnerService
	}
	return OwnerService_OWNER_SERVICE_UNSPECIFIED
}

func (x *FileLink) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *FileLink) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *FileLink) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *FileLink) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *FileLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UploadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInfo) Reset() {
	*x = UploadInfo{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInfo) ProtoMessage() {}

func (x *UploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInfo.ProtoReflect.Descriptor instead.
func (*UploadInfo) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *UploadInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UploadInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadInfo) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UploadInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type InitUploadRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MimeType          string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ExpectedSizeBytes int64                  `protobuf:"varint,2,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitUploadRequest) Reset() {
	*x = InitUploadRequest{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadRequest) ProtoMessage() {}

func (x *InitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadRequest.ProtoReflect.Descriptor instead.
func (*InitUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *InitUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *InitUploadRequest) GetExpectedSizeBytes() int64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

type InitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileObject            `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Upload        *UploadInfo            `protobuf:"bytes,2,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadResponse) Reset() {
	*x = InitUploadResponse{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadResponse) ProtoMessage() {}

func (x *InitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadResponse.ProtoReflect.Descriptor instead.
func (*InitUploadResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *InitUploadResponse) GetFile() *FileObject {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *InitUploadResponse) GetUpload() *UploadInfo {
	if x != nil {
		return x.Upload
	}
	return nil
}

type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileObject            `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmUploadResponse) GetFile() *FileObject {
	if x != nil {
		return x.File
	}
	return nil
}

type GetDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlRequest) Reset() {
	*x = GetDownloadUrlRequest{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlRequest) ProtoMessage() {}

func (x *GetDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *GetDownloadUrlRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *GetDownloadUrlResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetDownloadUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadUrlResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type BatchGetDownloadUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []string               `protobuf:"bytes,1,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetDownloadUrlsRequest) Reset() {
	*x = BatchGetDownloadUrlsRequest{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetDownloadUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetDownloadUrlsRequest) ProtoMessage() {}

func (x *BatchGetDownloadUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetDownloadUrlsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetDownloadUrlsRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetDownloadUrlsRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type BatchGetDownloadUrlsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*GetDownloadUrlResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetDownloadUrlsResponse) Reset() {
	*x = BatchGetDownloadUrlsResponse{}
	mi := &file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetDownloadUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetDownloadUrlsResponse) ProtoMessage() {}

func (x *BatchGetDownloadUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetDownloadUrlsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetDownloadUrlsResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetDownloadUrlsResponse) GetItems() []*GetDownloadUrlResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type LinkFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerService  OwnerService           `protobuf:"varint,2,opt,name=owner_service,json=ownerService,proto3,enum=file.OwnerService" json:"owner_service,omitempty"`
	OwnerType     string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PetId         string                 `protobuf:"bytes,5,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkFileRequest) Reset() {
	*x = LinkFileRequest{}
	mi := &file_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkFileRequest) ProtoMessage() {}

func (x *LinkFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkFileRequest.ProtoReflect.Descriptor instead.
func (*LinkFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{11}
}

func (x *LinkFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *LinkFileRequest) GetOwnerService() OwnerService {
	if x != nil {
		return x.OwnerService
	}
	return OwnerService_OWNER_SERVICE_UNSPECIFIED
}

func (x *LinkFileRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *LinkFileRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *LinkFileRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type LinkFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *FileLink              `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkFileResponse) Reset() {
	*x = LinkFileResponse{}
	mi := &file_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkFileResponse) ProtoMessage() {}

func (x *LinkFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkFileResponse.ProtoReflect.Descriptor instead.
func (*LinkFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{12}
}

func (x *LinkFileResponse) GetLink() *FileLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type UnlinkFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerService  OwnerService           `protobuf:"varint,2,opt,name=owner_service,json=ownerService,proto3,enum=file.OwnerService" json:"owner_service,omitempty"`
	OwnerType     string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkFileRequest) Reset() {
	*x = UnlinkFileRequest{}
	mi := &file_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkFileRequest) ProtoMessage() {}

func (x *UnlinkFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkFileRequest.ProtoReflect.Descriptor instead.
func (*UnlinkFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{13}
}

func (x *UnlinkFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UnlinkFileRequest) GetOwnerService() OwnerService {
	if x != nil {
		return x.OwnerService
	}
	return OwnerService_OWNER_SERVICE_UNSPECIFIED
}

func (x *UnlinkFileRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *UnlinkFileRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UnlinkFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkFileResponse) Reset() {
	*x = UnlinkFileResponse{}
	mi := &file_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkFileResponse) ProtoMessage() {}

func (x *UnlinkFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkFileResponse.ProtoReflect.Descriptor instead.
func (*UnlinkFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{14}
}

func (x *UnlinkFileResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{15}
}

func (x *GetFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileObject            `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{16}
}

func (x *GetFileResponse) GetFile() *FileObject {
	if x != nil {
		return x.File
	}
	return nil
}

type ListFileLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileLinksRequest) Reset() {
	*x = ListFileLinksRequest{}
	mi := &file_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileLinksRequest) ProtoMessage() {}

func (x *ListFileLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileLinksRequest.ProtoReflect.Descriptor instead.
func (*ListFileLinksRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{17}
}

func (x *ListFileLinksRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ListFileLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FileLink            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileLinksResponse) Reset() {
	*x = ListFileLinksResponse{}
	mi := &file_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileLinksResponse) ProtoMessage() {}

func (x *ListFileLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileLinksResponse.ProtoReflect.Descriptor instead.
func (*ListFileLinksResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{18}
}

func (x *ListFileLinksResponse) GetItems() []*FileLink {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x04file\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x03\n" +
	"\n" +
	"FileObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.file.FileStatusR\x06status\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x06 \x01(\tR\tobjectKey\x12+\n" +
	"\x12created_by_user_id\x18\a \x01(\tR\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\x11upload_expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0fuploadExpiresAt\"\xa5\x02\n" +
	"\bFileLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x127\n" +
	"\rowner_service\x18\x03 \x01(\x0e2\x12.file.OwnerServiceR\fownerService\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x04 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x15\n" +
	"\x06pet_id\x18\x06 \x01(\tR\x05petId\x12+\n" +
	"\x12created_by_user_id\x18\a \x01(\tR\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe6\x01\n" +
	"\n" +
	"UploadInfo\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x127\n" +
	"\aheaders\x18\x03 \x03(\v2\x1d.file.UploadInfo.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x11InitUploadRequest\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12.\n" +
	"\x13expected_size_bytes\x18\x02 \x01(\x03R\x11expectedSizeBytes\"d\n" +
	"\x12InitUploadResponse\x12$\n" +
	"\x04file\x18\x01 \x01(\v2\x10.file.FileObjectR\x04file\x12(\n" +
	"\x06upload\x18\x02 \x01(\v2\x10.file.UploadInfoR\x06upload\"N\n" +
	"\x14ConfirmUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"=\n" +
	"\x15ConfirmUploadResponse\x12$\n" +
	"\x04file\x18\x01 \x01(\v2\x10.file.FileObjectR\x04file\"0\n" +
	"\x15GetDownloadUrlRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"~\n" +
	"\x16GetDownloadUrlResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"8\n" +
	"\x1bBatchGetDownloadUrlsRequest\x12\x19\n" +
	"\bfile_ids\x18\x01 \x03(\tR\afileIds\"R\n" +
	"\x1cBatchGetDownloadUrlsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.file.GetDownloadUrlResponseR\x05items\"\xb4\x01\n" +
	"\x0fLinkFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x127\n" +
	"\rowner_service\x18\x02 \x01(\x0e2\x12.file.OwnerServiceR\fownerService\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x15\n" +
	"\x06pet_id\x18\x05 \x01(\tR\x05petId\"6\n" +
	"\x10LinkFileResponse\x12\"\n" +
	"\x04link\x18\x01 \x01(\v2\x0e.file.FileLinkR\x04link\"\x9f\x01\n" +
	"\x11UnlinkFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x127\n" +
	"\rowner_service\x18\x02 \x01(\x0e2\x12.file.OwnerServiceR\fownerService\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\".\n" +
	"\x12UnlinkFileResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\")\n" +
	"\x0eGetFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"7\n" +
	"\x0fGetFileResponse\x12$\n" +
	"\x04file\x18\x01 \x01(\v2\x10.file.FileObjectR\x04file\"/\n" +
	"\x14ListFileLinksRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"=\n" +
	"\x15ListFileLinksResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.file.FileLinkR\x05items*\x8c\x01\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FILE_STATUS_UPLOADING\x10\x01\x12\x15\n" +
	"\x11FILE_STATUS_READY\x10\x02\x12\x16\n" +
	"\x12FILE_STATUS_FAILED\x10\x03\x12\x17\n" +
	"\x13FILE_STATUS_DELETED\x10\x04*\xdc\x01\n" +
	"\fOwnerService\x12\x1d\n" +
	"\x19OWNER_SERVICE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OWNER_SERVICE_PROFILE\x10\x01\x12\x15\n" +
	"\x11OWNER_SERVICE_PET\x10\x02\x12\x17\n" +
	"\x13OWNER_SERVICE_GUIDE\x10\x03\x12\x15\n" +
	"\x11OWNER_SERVICE_LOG\x10\x04\x12\x18\n" +
	"\x14OWNER_SERVICE_HEALTH\x10\x05\x12\x16\n" +
	"\x12OWNER_SERVICE_CHAT\x10\x06\x12\x19\n" +
	"\x15OWNER_SERVICE_CATALOG\x10\a2\xc2\x04\n" +
	"\vFileService\x12?\n" +
	"\n" +
	"InitUpload\x12\x17.file.InitUploadRequest\x1a\x18.file.InitUploadResponse\x12H\n" +
	"\rConfirmUpload\x12\x1a.file.ConfirmUploadRequest\x1a\x1b.file.ConfirmUploadResponse\x12K\n" +
	"\x0eGetDownloadUrl\x12\x1b.file.GetDownloadUrlRequest\x1a\x1c.file.GetDownloadUrlResponse\x12]\n" +
	"\x14BatchGetDownloadUrls\x12!.file.BatchGetDownloadUrlsRequest\x1a\".file.BatchGetDownloadUrlsResponse\x129\n" +
	"\bLinkFile\x12\x15.file.LinkFileRequest\x1a\x16.file.LinkFileResponse\x12?\n" +
	"\n" +
	"UnlinkFile\x12\x17.file.UnlinkFileRequest\x1a\x18.file.UnlinkFileResponse\x126\n" +
	"\aGetFile\x12\x14.file.GetFileRequest\x1a\x15.file.GetFileResponse\x12H\n" +
	"\rListFileLinks\x12\x1a.file.ListFileLinksRequest\x1a\x1b.file.ListFileLinksResponseB&Z$file/internal/transport/proto;filepbb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_file_proto_goTypes = []any{
	(FileStatus)(0),                      // 0: file.FileStatus
	(OwnerService)(0),                    // 1: file.OwnerService
	(*FileObject)(nil),                   // 2: file.FileObject
	(*FileLink)(nil),                     // 3: file.FileLink
	(*UploadInfo)(nil),                   // 4: file.UploadInfo
	(*InitUploadRequest)(nil),            // 5: file.InitUploadRequest
	(*InitUploadResponse)(nil),           // 6: file.InitUploadResponse
	(*ConfirmUploadRequest)(nil),         // 7: file.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),        // 8: file.ConfirmUploadResponse
	(*GetDownloadUrlRequest)(nil),        // 9: file.GetDownloadUrlRequest
	(*GetDownloadUrlResponse)(nil),       // 10: file.GetDownloadUrlResponse
	(*BatchGetDownloadUrlsRequest)(nil),  // 11: file.BatchGetDownloadUrlsRequest
	(*BatchGetDownloadUrlsResponse)(nil), // 12: file.BatchGetDownloadUrlsResponse
	(*LinkFileRequest)(nil),              // 13: file.LinkFileRequest
	(*LinkFileResponse)(nil),             // 14: file.LinkFileResponse
	(*UnlinkFileRequest)(nil),            // 15: file.UnlinkFileRequest
	(*UnlinkFileResponse)(nil),           // 16: file.UnlinkFileResponse
	(*GetFileRequest)(nil),               // 17: file.GetFileRequest
	(*GetFileResponse)(nil),              // 18: file.GetFileResponse
	(*ListFileLinksRequest)(nil),         // 19: file.ListFileLinksRequest
	(*ListFileLinksResponse)(nil),        // 20: file.ListFileLinksResponse
	nil,                                  // 21: file.UploadInfo.HeadersEntry
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
}
var file_file_proto_depIdxs = []int32{
	0,  // 0: file.FileObject.status:type_name -> file.FileStatus
	22, // 1: file.FileObject.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: file.FileObject.updated_at:type_name -> google.protobuf.Timestamp
	22, // 3: file.FileObject.upload_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: file.FileLink.owner_service:type_name -> file.OwnerService
	22, // 5: file.FileLink.created_at:type_name -> google.protobuf.Timestamp
	21, // 6: file.UploadInfo.headers:type_name -> file.UploadInfo.HeadersEntry
	22, // 7: file.UploadInfo.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 8: file.InitUploadResponse.file:type_name -> file.FileObject
	4,  // 9: file.InitUploadResponse.upload:type_name -> file.UploadInfo
	2,  // 10: file.ConfirmUploadResponse.file:type_name -> file.FileObject
	22, // 11: file.GetDownloadUrlResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 12: file.BatchGetDownloadUrlsResponse.items:type_name -> file.GetDownloadUrlResponse
	1,  // 13: file.LinkFileRequest.owner_service:type_name -> file.OwnerService
	3,  // 14: file.LinkFileResponse.link:type_name -> file.FileLink
	1,  // 15: file.UnlinkFileRequest.owner_service:type_name -> file.OwnerService
	2,  // 16: file.GetFileResponse.file:type_name -> file.FileObject
	3,  // 17: file.ListFileLinksResponse.items:type_name -> file.FileLink
	5,  // 18: file.FileService.InitUpload:input_type -> file.InitUploadRequest
	7,  // 19: file.FileService.ConfirmUpload:input_type -> file.ConfirmUploadRequest
	9,  // 20: file.FileService.GetDownloadUrl:input_type -> file.GetDownloadUrlRequest
	11, // 21: file.FileService.BatchGetDownloadUrls:input_type -> file.BatchGetDownloadUrlsRequest
	13, // 22: file.FileService.LinkFile:input_type -> file.LinkFileRequest
	15, // 23: file.FileService.UnlinkFile:input_type -> file.UnlinkFileRequest
	17, // 24: file.FileService.GetFile:input_type -> file.GetFileRequest
	19, // 25: file.FileService.ListFileLinks:input_type -> file.ListFileLinksRequest
	6,  // 26: file.FileService.InitUpload:output_type -> file.InitUploadResponse
	8,  // 27: file.FileService.ConfirmUpload:output_type -> file.ConfirmUploadResponse
	10, // 28: file.FileService.GetDownloadUrl:output_type -> file.GetDownloadUrlResponse
	12, // 29: file.FileService.BatchGetDownloadUrls:output_type -> file.BatchGetDownloadUrlsResponse
	14, // 30: file.FileService.LinkFile:output_type -> file.LinkFileResponse
	16, // 31: file.FileService.UnlinkFile:output_type -> file.UnlinkFileResponse
	18, // 32: file.FileService.GetFile:output_type -> file.GetFileResponse
	20, // 33: file.FileService.ListFileLinks:output_type -> file.ListFileLinksResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		EnumInfos:         file_file_proto_enumTypes,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
