syntax = "proto3";

package profile;

option go_package = "profile/proto;profilepb";

service ProfileService {
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
  rpc DeleteProfile(DeleteProfileRequest) returns (DeleteProfileResponse);
  rpc GetPreferences(GetPreferencesRequest) returns (GetPreferencesResponse);
  rpc BatchGetPreferences(BatchGetPreferencesRequest) returns (BatchGetPreferencesResponse);
  rpc BatchProfilesBrief(BatchProfilesBriefRequest) returns (BatchProfilesBriefResponse);
}

message CreateProfileRequest {
  string user_id = 1;
  string locale = 2;
  string first_name = 3;
  string last_name = 4;
  string timezone = 5;
}

message CreateProfileResponse {
  string user_id = 1;
}

message DeleteProfileRequest {
  string user_id = 1;
}

message DeleteProfileResponse {
  string user_id = 1;
}

message GetPreferencesRequest {
  string user_id = 1;
}

message GetPreferencesResponse {
  string user_id = 1;
  string locale = 2;
  string timezone = 3;
}

message BatchGetPreferencesRequest {
  repeated string user_ids = 1;
}

message ProfilePreferences {
  string user_id = 1;
  string locale = 2;
  string timezone = 3;
}

message BatchGetPreferencesResponse {
  repeated ProfilePreferences items = 1;
  repeated string not_found_user_ids = 2;
}

message BatchProfilesBriefRequest {
  repeated string user_ids = 1;
}

message ProfileBrief {
  string user_id = 1;
  string first_name = 2;
  string last_name = 3;
  string display_name = 4;
  string avatar_download_url = 5;
}

message BatchProfilesBriefResponse {
  repeated ProfileBrief items = 1;
  repeated string not_found_user_ids = 2;
}
