// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/profile.proto

package profilepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateProfileRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_proto_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_proto_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_proto_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{5}
}

func (x *GetPreferencesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPreferencesResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *GetPreferencesResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type BatchGetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetPreferencesRequest) Reset() {
	*x = BatchGetPreferencesRequest{}
	mi := &file_proto_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPreferencesRequest) ProtoMessage() {}

func (x *BatchGetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetPreferencesRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ProfilePreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePreferences) Reset() {
	*x = ProfilePreferences{}
	mi := &file_proto_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePreferences) ProtoMessage() {}

func (x *ProfilePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePreferences.ProtoReflect.Descriptor instead.
func (*ProfilePreferences) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{7}
}

func (x *ProfilePreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfilePreferences) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *ProfilePreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type BatchGetPreferencesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*ProfilePreferences  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NotFoundUserIds []string               `protobuf:"bytes,2,rep,name=not_found_user_ids,json=notFoundUserIds,proto3" json:"not_found_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchGetPreferencesResponse) Reset() {
	*x = BatchGetPreferencesResponse{}
	mi := &file_proto_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetPreferencesResponse) ProtoMessage() {}

func (x *BatchGetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetPreferencesResponse) GetItems() []*ProfilePreferences {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchGetPreferencesResponse) GetNotFoundUserIds() []string {
	if x != nil {
		return x.NotFoundUserIds
	}
	return nil
}

type BatchProfilesBriefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchProfilesBriefRequest) Reset() {
	*x = BatchProfilesBriefRequest{}
	mi := &file_proto_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProfilesBriefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProfilesBriefRequest) ProtoMessage() {}

func (x *BatchProfilesBriefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProfilesBriefRequest.ProtoReflect.Descriptor instead.
func (*BatchProfilesBriefRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{9}
}

func (x *BatchProfilesBriefRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ProfileBrief struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName         string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DisplayName       string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarDownloadUrl string                 `protobuf:"bytes,5,opt,name=avatar_download_url,json=avatarDownloadUrl,proto3" json:"avatar_download_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileBrief) Reset() {
	*x = ProfileBrief{}
	mi := &file_proto_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileBrief) ProtoMessage() {}

func (x *ProfileBrief) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileBrief.ProtoReflect.Descriptor instead.
func (*ProfileBrief) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{10}
}

func (x *ProfileBrief) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileBrief) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileBrief) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileBrief) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileBrief) GetAvatarDownloadUrl() string {
	if x != nil {
		return x.AvatarDownloadUrl
	}
	return ""
}

type BatchProfilesBriefResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*ProfileBrief        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NotFoundUserIds []string               `protobuf:"bytes,2,rep,name=not_found_user_ids,json=notFoundUserIds,proto3" json:"not_found_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchProfilesBriefResponse) Reset() {
	*x = BatchProfilesBriefResponse{}
	mi := &file_proto_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProfilesBriefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProfilesBriefResponse) ProtoMessage() {}

func (x *BatchProfilesBriefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProfilesBriefResponse.ProtoReflect.Descriptor instead.
func (*BatchProfilesBriefResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{11}
}

func (x *BatchProfilesBriefResponse) GetItems() []*ProfileBrief {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchProfilesBriefResponse) GetNotFoundUserIds() []string {
	if x != nil {
		return x.NotFoundUserIds
	}
	return nil
}

var File_proto_profile_proto protoreflect.FileDescriptor

const file_proto_profile_proto_rawDesc = "" +
	"\n" +
	"\x13proto/profile.proto\x12\aprofile\"\x9f\x01\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\"0\n" +
	"\x15CreateProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x14DeleteProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x15DeleteProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"e\n" +
	"\x16GetPreferencesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"7\n" +
	"\x1aBatchGetPreferencesRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"a\n" +
	"\x12ProfilePreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"}\n" +
	"\x1bBatchGetPreferencesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.profile.ProfilePreferencesR\x05items\x12+\n" +
	"\x12not_found_user_ids\x18\x02 \x03(\tR\x0fnotFoundUserIds\"6\n" +
	"\x19BatchProfilesBriefRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xb6\x01\n" +
	"\fProfileBrief\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12.\n" +
	"\x13avatar_download_url\x18\x05 \x01(\tR\x11avatarDownloadUrl\"v\n" +
	"\x1aBatchProfilesBriefResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.profile.ProfileBriefR\x05items\x12+\n" +
	"\x12not_found_user_ids\x18\x02 \x03(\tR\x0fnotFoundUserIds2\xc4\x03\n" +
	"\x0eProfileService\x12N\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponse\x12N\n" +
	"\rDeleteProfile\x12\x1d.profile.DeleteProfileRequest\x1a\x1e.profile.DeleteProfileResponse\x12Q\n" +
	"\x0eGetPreferences\x12\x1e.profile.GetPreferencesRequest\x1a\x1f.profile.GetPreferencesResponse\x12`\n" +
	"\x13BatchGetPreferences\x12#.profile.BatchGetPreferencesRequest\x1a$.profile.BatchGetPreferencesResponse\x12]\n" +
	"\x12BatchProfilesBrief\x12\".profile.BatchProfilesBriefRequest\x1a#.profile.BatchProfilesBriefResponseB\x19Z\x17profile/proto;profilepbb\x06proto3"

var (
	file_proto_profile_proto_rawDescOnce sync.Once
	file_proto_profile_proto_rawDescData []byte
)

func file_proto_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)))
	})
	return file_proto_profile_proto_rawDescData
}

var file_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_profile_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),        // 0: profile.CreateProfileRequest
	(*CreateProfileResponse)(nil),       // 1: profile.CreateProfileResponse
	(*DeleteProfileRequest)(nil),        // 2: profile.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),       // 3: profile.DeleteProfileResponse
	(*GetPreferencesRequest)(nil),       // 4: profile.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),      // 5: profile.GetPreferencesResponse
	(*BatchGetPreferencesRequest)(nil),  // 6: profile.BatchGetPreferencesRequest
	(*ProfilePreferences)(nil),          // 7: profile.ProfilePreferences
	(*BatchGetPreferencesResponse)(nil), // 8: profile.BatchGetPreferencesResponse
	(*BatchProfilesBriefRequest)(nil),   // 9: profile.BatchProfilesBriefRequest
	(*ProfileBrief)(nil),                // 10: profile.ProfileBrief
	(*BatchProfilesBriefResponse)(nil),  // 11: profile.BatchProfilesBriefResponse
}
var file_proto_profile_proto_depIdxs = []int32{
	7,  // 0: profile.BatchGetPreferencesResponse.items:type_name -> profile.ProfilePreferences
	10, // 1: profile.BatchProfilesBriefResponse.items:type_name -> profile.ProfileBrief
	0,  // 2: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	2,  // 3: profile.ProfileService.DeleteProfile:input_type -> profile.DeleteProfileRequest
	4,  // 4: profile.ProfileService.GetPreferences:input_type -> profile.GetPreferencesRequest
	6,  // 5: profile.ProfileService.BatchGetPreferences:input_type -> profile.BatchGetPreferencesRequest
	9,  // 6: profile.ProfileService.BatchProfilesBrief:input_type -> profile.BatchProfilesBriefRequest
	1,  // 7: profile.ProfileService.CreateProfile:output_type -> profile.CreateProfileResponse
	3,  // 8: profile.ProfileService.DeleteProfile:output_type -> profile.DeleteProfileResponse
	5,  // 9: profile.ProfileService.GetPreferences:output_type -> profile.GetPreferencesResponse
	8,  // 10: profile.ProfileService.BatchGetPreferences:output_type -> profile.BatchGetPreferencesResponse
	11, // 11: profile.ProfileService.BatchProfilesBrief:output_type -> profile.BatchProfilesBriefResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_profile_proto_init() }
func file_proto_profile_proto_init() {
	if File_proto_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_proto = out.File
	file_proto_profile_proto_goTypes = nil
	file_proto_profile_proto_depIdxs = nil
}
