http:
  routers:
    gateway:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: gateway

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8081"
