// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/profilepb/profile.proto

package profilepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_profilepb_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profilepb_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profilepb_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_profilepb_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profilepb_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profilepb_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BatchProfilesBriefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchProfilesBriefRequest) Reset() {
	*x = BatchProfilesBriefRequest{}
	mi := &file_proto_profilepb_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProfilesBriefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProfilesBriefRequest) ProtoMessage() {}

func (x *BatchProfilesBriefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profilepb_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProfilesBriefRequest.ProtoReflect.Descriptor instead.
func (*BatchProfilesBriefRequest) Descriptor() ([]byte, []int) {
	return file_proto_profilepb_profile_proto_rawDescGZIP(), []int{2}
}

func (x *BatchProfilesBriefRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ProfileBrief struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName         string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DisplayName       string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarDownloadUrl string                 `protobuf:"bytes,5,opt,name=avatar_download_url,json=avatarDownloadUrl,proto3" json:"avatar_download_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileBrief) Reset() {
	*x = ProfileBrief{}
	mi := &file_proto_profilepb_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileBrief) ProtoMessage() {}

func (x *ProfileBrief) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profilepb_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileBrief.ProtoReflect.Descriptor instead.
func (*ProfileBrief) Descriptor() ([]byte, []int) {
	return file_proto_profilepb_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileBrief) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileBrief) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileBrief) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileBrief) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileBrief) GetAvatarDownloadUrl() string {
	if x != nil {
		return x.AvatarDownloadUrl
	}
	return ""
}

type BatchProfilesBriefResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*ProfileBrief        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NotFoundUserIds []string               `protobuf:"bytes,2,rep,name=not_found_user_ids,json=notFoundUserIds,proto3" json:"not_found_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchProfilesBriefResponse) Reset() {
	*x = BatchProfilesBriefResponse{}
	mi := &file_proto_profilepb_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProfilesBriefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProfilesBriefResponse) ProtoMessage() {}

func (x *BatchProfilesBriefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profilepb_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProfilesBriefResponse.ProtoReflect.Descriptor instead.
func (*BatchProfilesBriefResponse) Descriptor() ([]byte, []int) {
	return file_proto_profilepb_profile_proto_rawDescGZIP(), []int{4}
}

func (x *BatchProfilesBriefResponse) GetItems() []*ProfileBrief {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchProfilesBriefResponse) GetNotFoundUserIds() []string {
	if x != nil {
		return x.NotFoundUserIds
	}
	return nil
}

var File_proto_profilepb_profile_proto protoreflect.FileDescriptor

const file_proto_profilepb_profile_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/profilepb/profile.proto\x12\aprofile\"\x83\x01\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"0\n" +
	"\x15CreateProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x19BatchProfilesBriefRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xb6\x01\n" +
	"\fProfileBrief\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12.\n" +
	"\x13avatar_download_url\x18\x05 \x01(\tR\x11avatarDownloadUrl\"v\n" +
	"\x1aBatchProfilesBriefResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.profile.ProfileBriefR\x05items\x12+\n" +
	"\x12not_found_user_ids\x18\x02 \x03(\tR\x0fnotFoundUserIds2\xbf\x01\n" +
	"\x0eProfileService\x12N\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponse\x12]\n" +
	"\x12BatchProfilesBrief\x12\".profile.BatchProfilesBriefRequest\x1a#.profile.BatchProfilesBriefResponseB\x1fZ\x1dacl/proto/profilepb;profilepbb\x06proto3"

var (
	file_proto_profilepb_profile_proto_rawDescOnce sync.Once
	file_proto_profilepb_profile_proto_rawDescData []byte
)

func file_proto_profilepb_profile_proto_rawDescGZIP() []byte {
	file_proto_profilepb_profile_proto_rawDescOnce.Do(func() {
		file_proto_profilepb_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profilepb_profile_proto_rawDesc), len(file_proto_profilepb_profile_proto_rawDesc)))
	})
	return file_proto_profilepb_profile_proto_rawDescData
}

var file_proto_profilepb_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_profilepb_profile_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),       // 0: profile.CreateProfileRequest
	(*CreateProfileResponse)(nil),      // 1: profile.CreateProfileResponse
	(*BatchProfilesBriefRequest)(nil),  // 2: profile.BatchProfilesBriefRequest
	(*ProfileBrief)(nil),               // 3: profile.ProfileBrief
	(*BatchProfilesBriefResponse)(nil), // 4: profile.BatchProfilesBriefResponse
}
var file_proto_profilepb_profile_proto_depIdxs = []int32{
	3, // 0: profile.BatchProfilesBriefResponse.items:type_name -> profile.ProfileBrief
	0, // 1: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	2, // 2: profile.ProfileService.BatchProfilesBrief:input_type -> profile.BatchProfilesBriefRequest
	1, // 3: profile.ProfileService.CreateProfile:output_type -> profile.CreateProfileResponse
	4, // 4: profile.ProfileService.BatchProfilesBrief:output_type -> profile.BatchProfilesBriefResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_profilepb_profile_proto_init() }
func file_proto_profilepb_profile_proto_init() {
	if File_proto_profilepb_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profilepb_profile_proto_rawDesc), len(file_proto_profilepb_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profilepb_profile_proto_goTypes,
		DependencyIndexes: file_proto_profilepb_profile_proto_depIdxs,
		MessageInfos:      file_proto_profilepb_profile_proto_msgTypes,
	}.Build()
	File_proto_profilepb_profile_proto = out.File
	file_proto_profilepb_profile_proto_goTypes = nil
	file_proto_profilepb_profile_proto_depIdxs = nil
}
