// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: acl.proto

package aclpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED              Action = 0
	Action_ACTION_PET_READ                 Action = 1
	Action_ACTION_PET_EDIT                 Action = 2
	Action_ACTION_PET_STATUS_CHANGE        Action = 3
	Action_ACTION_PET_DELETE               Action = 4
	Action_ACTION_LOG_READ                 Action = 5
	Action_ACTION_LOG_CREATE               Action = 6
	Action_ACTION_LOG_EDIT                 Action = 7
	Action_ACTION_LOG_DELETE               Action = 8
	Action_ACTION_LOG_ATTACHMENTS_READ     Action = 9
	Action_ACTION_HEALTH_READ              Action = 10
	Action_ACTION_HEALTH_WRITE             Action = 11
	Action_ACTION_TASK_READ                Action = 12
	Action_ACTION_TASK_WRITE               Action = 13
	Action_ACTION_MEMBERS_VIEW             Action = 14
	Action_ACTION_MEMBERS_INVITE           Action = 15
	Action_ACTION_MEMBERS_REMOVE           Action = 16
	Action_ACTION_MEMBERS_EDIT_PERMISSIONS Action = 17
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		1:  "ACTION_PET_READ",
		2:  "ACTION_PET_EDIT",
		3:  "ACTION_PET_STATUS_CHANGE",
		4:  "ACTION_PET_DELETE",
		5:  "ACTION_LOG_READ",
		6:  "ACTION_LOG_CREATE",
		7:  "ACTION_LOG_EDIT",
		8:  "ACTION_LOG_DELETE",
		9:  "ACTION_LOG_ATTACHMENTS_READ",
		10: "ACTION_HEALTH_READ",
		11: "ACTION_HEALTH_WRITE",
		12: "ACTION_TASK_READ",
		13: "ACTION_TASK_WRITE",
		14: "ACTION_MEMBERS_VIEW",
		15: "ACTION_MEMBERS_INVITE",
		16: "ACTION_MEMBERS_REMOVE",
		17: "ACTION_MEMBERS_EDIT_PERMISSIONS",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":              0,
		"ACTION_PET_READ":                 1,
		"ACTION_PET_EDIT":                 2,
		"ACTION_PET_STATUS_CHANGE":        3,
		"ACTION_PET_DELETE":               4,
		"ACTION_LOG_READ":                 5,
		"ACTION_LOG_CREATE":               6,
		"ACTION_LOG_EDIT":                 7,
		"ACTION_LOG_DELETE":               8,
		"ACTION_LOG_ATTACHMENTS_READ":     9,
		"ACTION_HEALTH_READ":              10,
		"ACTION_HEALTH_WRITE":             11,
		"ACTION_TASK_READ":                12,
		"ACTION_TASK_WRITE":               13,
		"ACTION_MEMBERS_VIEW":             14,
		"ACTION_MEMBERS_INVITE":           15,
		"ACTION_MEMBERS_REMOVE":           16,
		"ACTION_MEMBERS_EDIT_PERMISSIONS": 17,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=acl.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *CheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type ListPetsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsForUserRequest) Reset() {
	*x = ListPetsForUserRequest{}
	mi := &file_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsForUserRequest) ProtoMessage() {}

func (x *ListPetsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsForUserRequest.ProtoReflect.Descriptor instead.
func (*ListPetsForUserRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{2}
}

func (x *ListPetsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPetsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetIds        []string               `protobuf:"bytes,1,rep,name=pet_ids,json=petIds,proto3" json:"pet_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsForUserResponse) Reset() {
	*x = ListPetsForUserResponse{}
	mi := &file_acl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsForUserResponse) ProtoMessage() {}

func (x *ListPetsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsForUserResponse.ProtoReflect.Descriptor instead.
func (*ListPetsForUserResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{3}
}

func (x *ListPetsForUserResponse) GetPetIds() []string {
	if x != nil {
		return x.PetIds
	}
	return nil
}

type CreateOwnerMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerMembershipRequest) Reset() {
	*x = CreateOwnerMembershipRequest{}
	mi := &file_acl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerMembershipRequest) ProtoMessage() {}

func (x *CreateOwnerMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateOwnerMembershipRequest) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOwnerMembershipRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *CreateOwnerMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateOwnerMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerMembershipResponse) Reset() {
	*x = CreateOwnerMembershipResponse{}
	mi := &file_acl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerMembershipResponse) ProtoMessage() {}

func (x *CreateOwnerMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerMembershipResponse.ProtoReflect.Descriptor instead.
func (*CreateOwnerMembershipResponse) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOwnerMembershipResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_acl_proto protoreflect.FileDescriptor

const file_acl_proto_rawDesc = "" +
	"\n" +
	"\tacl.proto\x12\x03acl\"c\n" +
	"\fCheckRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\x06action\x18\x03 \x01(\x0e2\v.acl.ActionR\x06action\")\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"1\n" +
	"\x16ListPetsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x17ListPetsForUserResponse\x12\x17\n" +
	"\apet_ids\x18\x01 \x03(\tR\x06petIds\"N\n" +
	"\x1cCreateOwnerMembershipRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"<\n" +
	"\x1dCreateOwnerMembershipResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId*\xca\x03\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_PET_READ\x10\x01\x12\x13\n" +
	"\x0fACTION_PET_EDIT\x10\x02\x12\x1c\n" +
	"\x18ACTION_PET_STATUS_CHANGE\x10\x03\x12\x15\n" +
	"\x11ACTION_PET_DELETE\x10\x04\x12\x13\n" +
	"\x0fACTION_LOG_READ\x10\x05\x12\x15\n" +
	"\x11ACTION_LOG_CREATE\x10\x06\x12\x13\n" +
	"\x0fACTION_LOG_EDIT\x10\a\x12\x15\n" +
	"\x11ACTION_LOG_DELETE\x10\b\x12\x1f\n" +
	"\x1bACTION_LOG_ATTACHMENTS_READ\x10\t\x12\x16\n" +
	"\x12ACTION_HEALTH_READ\x10\n" +
	"\x12\x17\n" +
	"\x13ACTION_HEALTH_WRITE\x10\v\x12\x14\n" +
	"\x10ACTION_TASK_READ\x10\f\x12\x15\n" +
	"\x11ACTION_TASK_WRITE\x10\r\x12\x17\n" +
	"\x13ACTION_MEMBERS_VIEW\x10\x0e\x12\x19\n" +
	"\x15ACTION_MEMBERS_INVITE\x10\x0f\x12\x19\n" +
	"\x15ACTION_MEMBERS_REMOVE\x10\x10\x12#\n" +
	"\x1fACTION_MEMBERS_EDIT_PERMISSIONS\x10\x112\xea\x01\n" +
	"\n" +
	"ACLService\x12.\n" +
	"\x05Check\x12\x11.acl.CheckRequest\x1a\x12.acl.CheckResponse\x12L\n" +
	"\x0fListPetsForUser\x12\x1b.acl.ListPetsForUserRequest\x1a\x1c.acl.ListPetsForUserResponse\x12^\n" +
	"\x15CreateOwnerMembership\x12!.acl.CreateOwnerMembershipRequest\x1a\".acl.CreateOwnerMembershipResponseB\x11Z\x0fpet/proto;aclpbb\x06proto3"

var (
	file_acl_proto_rawDescOnce sync.Once
	file_acl_proto_rawDescData []byte
)

func file_acl_proto_rawDescGZIP() []byte {
	file_acl_proto_rawDescOnce.Do(func() {
		file_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)))
	})
	return file_acl_proto_rawDescData
}

var file_acl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_acl_proto_goTypes = []any{
	(Action)(0),                           // 0: acl.Action
	(*CheckRequest)(nil),                  // 1: acl.CheckRequest
	(*CheckResponse)(nil),                 // 2: acl.CheckResponse
	(*ListPetsForUserRequest)(nil),        // 3: acl.ListPetsForUserRequest
	(*ListPetsForUserResponse)(nil),       // 4: acl.ListPetsForUserResponse
	(*CreateOwnerMembershipRequest)(nil),  // 5: acl.CreateOwnerMembershipRequest
	(*CreateOwnerMembershipResponse)(nil), // 6: acl.CreateOwnerMembershipResponse
}
var file_acl_proto_depIdxs = []int32{
	0, // 0: acl.CheckRequest.action:type_name -> acl.Action
	1, // 1: acl.ACLService.Check:input_type -> acl.CheckRequest
	3, // 2: acl.ACLService.ListPetsForUser:input_type -> acl.ListPetsForUserRequest
	5, // 3: acl.ACLService.CreateOwnerMembership:input_type -> acl.CreateOwnerMembershipRequest
	2, // 4: acl.ACLService.Check:output_type -> acl.CheckResponse
	4, // 5: acl.ACLService.ListPetsForUser:output_type -> acl.ListPetsForUserResponse
	6, // 6: acl.ACLService.CreateOwnerMembership:output_type -> acl.CreateOwnerMembershipResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_acl_proto_init() }
func file_acl_proto_init() {
	if File_acl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acl_proto_rawDesc), len(file_acl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acl_proto_goTypes,
		DependencyIndexes: file_acl_proto_depIdxs,
		EnumInfos:         file_acl_proto_enumTypes,
		MessageInfos:      file_acl_proto_msgTypes,
	}.Build()
	File_acl_proto = out.File
	file_acl_proto_goTypes = nil
	file_acl_proto_depIdxs = nil
}
